apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-secret-sync
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-secret-sync
  template:
    metadata:
      labels:
        app: cloudflare-secret-sync
    spec:
      containers:
        - name: secret-holder
          image: busybox:latest
          command:
            - sleep
            - infinity
          volumeMounts:
            - name: cloudflare-secret
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: cloudflare-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloudflare-api-token
