apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{CUSTOMER_NAME}}-db
spec:
  instances: 3

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: {{CUSTOMER_NAME}}-db-credentials

  storage:
    size: 1Gi
