apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: customer3-db
spec:
  instances: 3

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: customer3-db-credentials

  storage:
    size: 1Gi
